---
- name: Deploy Docker container
  hosts: your_server_group
  become: true

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: latest

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Run Docker container
      docker_container:
        name: application
        image: matveyguralkiy/application:V1.0
        ports:
          - "80:80"